apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::177335591239:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-i4GD9A0ijyno
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
        rolearn: arn:aws:iam::177335591239:role/UdacityFlaskDeployCBKubectlRole
